---
# tasks file for raid
- name: install mdadm
  yum:
    name: mdadm
    state: present
    update_cache: true
  tags: mdadm_install

- name: create directory /etc/mdadm/
  file:
    path: /etc/mdadm
    state: directory

- name: create raid
  shell: mdadm --create /dev/md127 -l 10 -n 4 /dev/sd{b..e}

- name: create mdadm.conf
  shell: |
    echo "DEVICE partitions" > /etc/mdadm/mdadm.conf;\
    mdadm --detail --scan --verbose | awk '/ARRAY/ {print}' >> /etc/mdadm/mdadm.conf
  tags: mdadm.conf

- name: create txt
  shell: |
    echo -e "1. RAID10 was created:\n" > /home/vagrant/mdstat.txt;\
    cat /proc/mdstat >> /home/vagrant/mdstat.txt;\
    echo -e "1. RAID10 was created:\n" > /home/vagrant/lsblk.txt;\
    lsblk >> /home/vagrant/lsblk.txt

- name: fail disk4
  shell: mdadm /dev/md127 --fail /dev/sdd

- name: edit txt
  shell: |
    printf '%.0s_' {1..50} >> /home/vagrant/mdstat.txt;\
    echo -e "\n\n2. Disk sdd was failed\n" >> /home/vagrant/mdstat.txt;\
    cat /proc/mdstat >> /home/vagrant/mdstat.txt;\
    printf '%.0s_' {1..50} >> /home/vagrant/lsblk.txt;\
    echo -e "\n\n2. Disk sdd was failed\n" >> /home/vagrant/lsblk.txt;\
    lsblk >> /home/vagrant/lsblk.txt


- name: change disk
  shell: |
    mdadm /dev/md127 --remove /dev/sdd;
    mdadm /dev/md127 --add /dev/sdf

- name: edit txt2
  shell: |
    printf '%.0s_' {1..50} >> /home/vagrant/mdstat.txt;\
    echo -e "\n\n3. Disk sdd was changed to sdf\n" >> /home/vagrant/mdstat.txt;\
    cat /proc/mdstat >> /home/vagrant/mdstat.txt;\
    printf '%.0s_' {1..50} >> /home/vagrant/lsblk.txt;\
    echo -e "\n\n3. Disk sdd was changed to sdf\n" >> /home/vagrant/lsblk.txt;\
    lsblk >> /home/vagrant/lsblk.txt

- name: partitions
  shell: |
    parted -s /dev/md127 mklabel gpt;
    echo "Ignore" | parted /dev/md127 mkpart primary ext4 0% 20%;
    parted /dev/md127 mkpart primary ext4 20% 40%;
    parted /dev/md127 mkpart primary ext4 40% 60%;
    parted /dev/md127 mkpart primary ext4 60% 80%;
    parted /dev/md127 mkpart primary ext4 80% 100%;

- name: filesystem
  shell: for i in $(seq 1 5); do sudo mkfs.ext4 /dev/md127p$i; done

- name: edit txt3
  shell: |
    printf '%.0s_' {1..50} >> /home/vagrant/lsblk.txt;\
    echo -e "\n\n4. Partitions\n" >> /home/vagrant/lsblk.txt;\
    lsblk >> /home/vagrant/lsblk.txt


- name: create directory /mnt/
  file:
    path: /mnt/part{{ item }}
    state: directory
  loop:
    - 1
    - 2
    - 3
    - 4
    - 5

- name: mount
  shell: |
    echo "/dev/md127p{{ item }} /mnt/part{{ item }} ext4 defaults 0 0" >> /etc/fstab;\
    mount /dev/md127p{{ item }}
  loop:
    - 1
    - 2
    - 3
    - 4
    - 5
